# Employee Data Analysis using Python and Pandas

In [1]:
import pandas as pd

In [2]:
# --------------------------------------------------
# 1. Import the dataset
# --------------------------------------------------

employee_data = pd.read_csv("employee_data.csv")

In [3]:
print("=" * 60)
print("EMPLOYEE DATA ANALYSIS")
print("=" * 60)

============================================================
EMPLOYEE DATA ANALYSIS
============================================================

In [5]:
# --------------------------------------------------
# 2. Display the first 5 records
# --------------------------------------------------

print("\n1. First 5 Records:")
employee_data.head()

1. First 5 Records:

,Employee ID,Employee Name,Department,Designation,Salary,Experience (Years),Age,Joining Date
0,EMP001,Ali Raza,IT,Software Engineer,85000,3,25,2022-03-15
1,EMP002,Ayesha Khan,HR,HR Executive,65000,4,28,2021-07-10
2,EMP003,Hamza Ahmed,Finance,Accountant,72000,5,30,2020-01-20
3,EMP004,Sara Malik,IT,Data Analyst,90000,4,27,2021-05-12
4,EMP005,Usman Tariq,Marketing,Marketing Executive,68000,3,26,2022-08-18

In [7]:
# --------------------------------------------------
# 3. Display the last 5 records
# --------------------------------------------------

print("\n2. Last 5 Records:")
employee_data.tail()

2. Last 5 Records:

,Employee ID,Employee Name,Department,Designation,Salary,Experience (Years),Age,Joining Date
20,EMP021,Rehan Akram,Marketing,SEO Specialist,75000,5,30,2020-06-30
21,EMP022,Komal Yousaf,HR,Training Officer,70000,5,31,2020-09-14
22,EMP023,Waleed Hussain,Sales,Sales Manager,108000,9,37,2016-12-05
23,EMP024,Noor Fatima,Finance,Financial Analyst,87000,4,28,2021-03-18
24,EMP025,Talha Javed,IT,Cloud Engineer,130000,12,41,2013-08-25

In [9]:
# --------------------------------------------------
# 4. Check dataset information
# --------------------------------------------------

print("\n3. Dataset Information:")
employee_data.info()

3. Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee ID         25 non-null     str
 1   Employee Name       25 non-null     str
 2   Department          25 non-null     str
 3   Designation         25 non-null     str
 4   Salary              25 non-null     int64
 5   Experience (Years)  25 non-null     int64
 6   Age                 25 non-null     int64
 7   Joining Date        25 non-null     str
dtypes: int64(3), str(5)
memory usage: 2.8 KB

In [10]:
# --------------------------------------------------
# 5. Display summary statistics
# --------------------------------------------------

print("\n4. Summary Statistics:")
print(employee_data.describe())

4. Summary Statistics:
              Salary  Experience (Years)        Age
count      25.000000            25.00000  25.000000
mean    87440.000000             5.48000  30.360000
std     22496.444163             2.95973   5.211206
min     55000.000000             1.00000  22.000000
25%     68000.000000             3.00000  27.000000
50%     87000.000000             5.00000  30.000000
75%    105000.000000             7.00000  34.000000
max    130000.000000            12.00000  41.000000

In [11]:
# --------------------------------------------------
# 6. Calculate the average salary
# --------------------------------------------------

average_salary = employee_data["Salary"].mean()

print("\n5. Average Salary:")
print(f"{average_salary:,.2f}")

5. Average Salary:
87,440.00

In [12]:
# --------------------------------------------------
# 7. Find the employee with the highest salary
# --------------------------------------------------

highest_salary_employee = employee_data.loc[
    employee_data["Salary"].idxmax()
]

print("\n6. Employee with the Highest Salary:")
print(highest_salary_employee)

6. Employee with the Highest Salary:
Employee ID                   EMP025
Employee Name            Talha Javed
Department                        IT
Designation           Cloud Engineer
Salary                        130000
Experience (Years)                12
Age                               41
Joining Date              2013-08-25
Name: 24, dtype: object

In [13]:
# --------------------------------------------------
# 8. Find the employee with the most experience
# --------------------------------------------------

most_experienced_employee = employee_data.loc[
    employee_data["Experience (Years)"].idxmax()
]

print("\n7. Employee with the Most Experience:")
print(most_experienced_employee)

7. Employee with the Most Experience:
Employee ID                   EMP025
Employee Name            Talha Javed
Department                        IT
Designation           Cloud Engineer
Salary                        130000
Experience (Years)                12
Age                               41
Joining Date              2013-08-25
Name: 24, dtype: object

In [15]:
# --------------------------------------------------
# 9. Display employees with salary greater than 80,000
# --------------------------------------------------

high_salary_employees = employee_data[
    employee_data["Salary"] > 80000
]

print("\n8. Employees with Salary Greater Than 80,000:")
high_salary_employees

8. Employees with Salary Greater Than 80,000:

,Employee ID,Employee Name,Department,Designation,Salary,Experience (Years),Age,Joining Date
0,EMP001,Ali Raza,IT,Software Engineer,85000,3,25,2022-03-15
3,EMP004,Sara Malik,IT,Data Analyst,90000,4,27,2021-05-12
5,EMP006,Fatima Noor,IT,Senior Developer,120000,7,32,2018-02-14
8,EMP009,Omar Farooq,Finance,Financial Analyst,95000,6,31,2019-04-17
9,EMP010,Maria Iqbal,IT,Software Developer,88000,4,28,2021-09-05
10,EMP011,Ahmed Hassan,Sales,Sales Manager,105000,8,35,2017-11-11
11,EMP012,Zainab Ali,Marketing,Marketing Manager,110000,9,36,2016-03-22
12,EMP013,Saad Khan,IT,DevOps Engineer,115000,6,31,2019-08-13
13,EMP014,Maham Raza,Finance,Senior Accountant,98000,7,34,2018-10-01
14,EMP015,Daniyal Ahmed,HR,HR Manager,100000,10,38,2015-05-19
18,EMP019,Arham Siddiqui,Finance,Finance Manager,125000,11,40,2014-07-16
19,EMP020,Anam Fatima,IT,UI UX Designer,82000,4,29,2021-11-23
22,EMP023,Waleed Hussain,Sales,Sales Manager,108000,9,37,2016-12-05
23,EMP024,Noor Fatima,Finance,Financial Analyst,87000,4,28,2021-03-18
24,EMP025,Talha Javed,IT,Cloud Engineer,130000,12,41,2013-08-25

In [16]:
# --------------------------------------------------
# 10. Find department with the highest average salary
# --------------------------------------------------

department_average_salary = employee_data.groupby(
    "Department"
)["Salary"].mean()

highest_average_salary_department = department_average_salary.idxmax()
highest_department_salary = department_average_salary.max()

print("\n9. Department with the Highest Average Salary:")
print(f"Department: {highest_average_salary_department}")
print(f"Average Salary: {highest_department_salary:,.2f}")

9. Department with the Highest Average Salary:
Department: IT
Average Salary: 95,625.00

In [17]:
# --------------------------------------------------
# 11. Count employees in each department
# --------------------------------------------------

department_employee_count = employee_data[
    "Department"
].value_counts()

print("\n10. Number of Employees in Each Department:")
print(department_employee_count)

10. Number of Employees in Each Department:
Department
IT           8
Finance      5
HR           4
Marketing    4
Sales        4
Name: count, dtype: int64

In [19]:
# --------------------------------------------------
# 12. Sort dataset by salary in descending order
# --------------------------------------------------

sorted_employee_data = employee_data.sort_values(
    by="Salary",
    ascending=False
)

print("\n11. Employees Sorted by Salary (Descending):")
sorted_employee_data

11. Employees Sorted by Salary (Descending):

,Employee ID,Employee Name,Department,Designation,Salary,Experience (Years),Age,Joining Date
24,EMP025,Talha Javed,IT,Cloud Engineer,130000,12,41,2013-08-25
18,EMP019,Arham Siddiqui,Finance,Finance Manager,125000,11,40,2014-07-16
5,EMP006,Fatima Noor,IT,Senior Developer,120000,7,32,2018-02-14
12,EMP013,Saad Khan,IT,DevOps Engineer,115000,6,31,2019-08-13
11,EMP012,Zainab Ali,Marketing,Marketing Manager,110000,9,36,2016-03-22
22,EMP023,Waleed Hussain,Sales,Sales Manager,108000,9,37,2016-12-05
10,EMP011,Ahmed Hassan,Sales,Sales Manager,105000,8,35,2017-11-11
14,EMP015,Daniyal Ahmed,HR,HR Manager,100000,10,38,2015-05-19
13,EMP014,Maham Raza,Finance,Senior Accountant,98000,7,34,2018-10-01
8,EMP009,Omar Farooq,Finance,Financial Analyst,95000,6,31,2019-04-17
3,EMP004,Sara Malik,IT,Data Analyst,90000,4,27,2021-05-12
9,EMP010,Maria Iqbal,IT,Software Developer,88000,4,28,2021-09-05
23,EMP024,Noor Fatima,Finance,Financial Analyst,87000,4,28,2021-03-18
0,EMP001,Ali Raza,IT,Software Engineer,85000,3,25,2022-03-15
19,EMP020,Anam Fatima,IT,UI UX Designer,82000,4,29,2021-11-23
20,EMP021,Rehan Akram,Marketing,SEO Specialist,75000,5,30,2020-06-30
2,EMP003,Hamza Ahmed,Finance,Accountant,72000,5,30,2020-01-20
21,EMP022,Komal Yousaf,HR,Training Officer,70000,5,31,2020-09-14
4,EMP005,Usman Tariq,Marketing,Marketing Executive,68000,3,26,2022-08-18
1,EMP002,Ayesha Khan,HR,HR Executive,65000,4,28,2021-07-10
17,EMP018,Mehwish Khan,Sales,Sales Executive,63000,3,26,2022-04-08
7,EMP008,Hira Aslam,HR,Recruiter,62000,3,27,2022-06-21
6,EMP007,Bilal Shah,Sales,Sales Executive,60000,2,24,2023-01-09
15,EMP016,Laiba Tariq,Marketing,Content Writer,58000,2,23,2023-02-27
16,EMP017,Shahzaib Malik,IT,Junior Developer,55000,1,22,2024-01-15

In [20]:
# --------------------------------------------------
# 13. Save the analyzed dataset
# --------------------------------------------------

sorted_employee_data.to_csv(
    "employee_analysis.csv",
    index=False
)

print("\n12. Analysis completed successfully!")
print("The analyzed dataset has been saved as 'employee_analysis.csv'.")

12. Analysis completed successfully!
The analyzed dataset has been saved as 'employee_analysis.csv'.